name: Trunk Check
on: [push]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk-check:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
